### ISSUE TITLE
InvalidCastException thrown when querying for `Any` on a sqlite database

### ISSUE THREAD

**Issue by icnocop** [moozzyk/EFCache#42]
Hi.

When I call the `Any` LINQ to Entities query on a sqlite database table with EFCache initialized, an `InvalidCastException` is thrown.

It can be reproduced using my fork here:
https://github.com/icnocop/EFCache

Compile and run the test `sqliteTest` (net462).

```
System.InvalidOperationException : The specified cast from a materialized 'System.Int64' type to the 'System.Boolean' type is not valid.
at System.Data.Entity.Core.Common.Internal.Materialization.Shaper.ErrorHandlingValueReader`1.GetValue(DbDataReader reader, Int32 ordinal)
   at lambda_method(Closure , Shaper )
   at System.Data.Entity.Core.Common.Internal.Materialization.Coordinator`1.ReadNextElement(Shaper shaper)
   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.SimpleEnumerator.MoveNext()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.<>c__14`1.<GetElementFunction>b__14_3(IEnumerable`1 sequence)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Any[TSource](IQueryable`1 source, Expression`1 predicate)
   at EFCache.E2ETest.sqliteTest() in E:\github\icnocop\EFCache\test\EFCacheTests\E2ETest.cs:line 330
```

Any ideas?

Thank you.

**Comment by moozzyk** [comment]
I have never tried SqlLite and am not sure why this is happening.

**Comment by moozzyk** [comment]
Seems like a mismatch at the provider level because [this](https://stackoverflow.com/questions/2510652/is-there-a-boolean-literal-in-sqlite) tells me that Sqlite does not have a boolean type.

**Comment by icnocop** [comment]
If I debug the test, the exception is thrown in https://github.com/moozzyk/EFCache/blob/3986f8c15b1c484f73653567a22a7482be291f7a/src/EFCache/CachingReader.cs#L59

**Comment by moozzyk** [comment]
This makes sense - GetValue reads the value from the column and assumes that type will be bool. I guess it could be fixed by checking the type and if it is one of the integral types return `GetValue(ordinal) != 0` instead of casting. It potentially can have some perf impact.

**Comment by icnocop** [comment]
Thank you.

In order to avoid having to replace that method with something like this:
```
        public override bool GetBoolean(int ordinal)
        {
            object value = GetValue(ordinal);
            if (value is bool)
            {
                return (bool)value;
            }
            else if (value is int)
            {
                return (int)value != 0;
            }
            // etc.

            return (long)value != 0;
        }
```

I'm wondering if it's possible to implement a generic DbDataReader class that delegates to the underlying provider-specific DbDataReader.

For example:
```
abstract class DelegatingDbDataReader : DbDataReader
{
    readonly DbDataReader source;
    public DelegatingDbDataReader(DbDataReader source)
    {
        this.source = source;
    }
    public override object this[string name] { get { return source[name]; } }
    public override object this[int ordinal] { get { return source[ordinal]; } }
    public override int Depth { get { return source.Depth; } }
    public override int FieldCount { get { return source.FieldCount; } }
    public override bool HasRows { get { return source.HasRows; } }
    public override bool IsClosed { get { return source.IsClosed; } }
    public override int RecordsAffected { get { return source.RecordsAffected; } }
    public override bool GetBoolean(int ordinal) { return source.GetBoolean(ordinal); }
    public override byte GetByte(int ordinal) { return source.GetByte(ordinal); }
    public override long GetBytes(int ordinal, long dataOffset, byte[] buffer, int bufferOffset, int length) { return source.GetBytes(ordinal, dataOffset, buffer, bufferOffset, length); }
    public override char GetChar(int ordinal) { return source.GetChar(ordinal); }
    public override long GetChars(int ordinal, long dataOffset, char[] buffer, int bufferOffset, int length) { return source.GetChars(ordinal, dataOffset, buffer, bufferOffset, length); }
    public override string GetDataTypeName(int ordinal) { return source.GetDataTypeName(ordinal); }
    public override DateTime GetDateTime(int ordinal) { return source.GetDateTime(ordinal); }
    public override decimal GetDecimal(int ordinal) { return source.GetDecimal(ordinal); }
    public override double GetDouble(int ordinal) { return source.GetDouble(ordinal); }
    public override IEnumerator GetEnumerator() { return source.GetEnumerator(); }
    public override Type GetFieldType(int ordinal) { return source.GetFieldType(ordinal); }
    public override float GetFloat(int ordinal) { return source.GetFloat(ordinal); }
    public override Guid GetGuid(int ordinal) { return source.GetGuid(ordinal); }
    public override short GetInt16(int ordinal) { return source.GetInt16(ordinal); }
    public override int GetInt32(int ordinal) { return source.GetInt32(ordinal); }
    public override long GetInt64(int ordinal) { return source.GetInt64(ordinal); }
    public override string GetName(int ordinal) { return source.GetName(ordinal); }
    public override int GetOrdinal(string name) { return source.GetOrdinal(name); }
    public override string GetString(int ordinal) { return source.GetString(ordinal); }
    public override object GetValue(int ordinal) { return source.GetValue(ordinal); }
    public override int GetValues(object[] values) { return source.GetValues(values); }
    public override bool IsDBNull(int ordinal) { return source.IsDBNull(ordinal); }
    public override bool NextResult() { return source.NextResult(); }
    public override bool Read() { return source.Read(); }
    public override void Close() { source.Close(); }
    public override T GetFieldValue<T>(int ordinal) { return source.GetFieldValue<T>(ordinal); }
    public override Task<T> GetFieldValueAsync<T>(int ordinal, CancellationToken cancellationToken) { return source.GetFieldValueAsync<T>(ordinal, cancellationToken); }
    public override Type GetProviderSpecificFieldType(int ordinal) { return source.GetProviderSpecificFieldType(ordinal); }
    public override object GetProviderSpecificValue(int ordinal) { return source.GetProviderSpecificValue(ordinal); }
    public override int GetProviderSpecificValues(object[] values) { return source.GetProviderSpecificValues(values); }
    public override DataTable GetSchemaTable() { return source.GetSchemaTable(); }
    public override Stream GetStream(int ordinal) { return source.GetStream(ordinal); }
    public override TextReader GetTextReader(int ordinal) { return source.GetTextReader(ordinal); }
    public override Task<bool> IsDBNullAsync(int ordinal, CancellationToken cancellationToken) { return source.IsDBNullAsync(ordinal, cancellationToken); }
    public override Task<bool> ReadAsync(CancellationToken cancellationToken) { return source.ReadAsync(cancellationToken); }
    public override int VisibleFieldCount { get { return source.VisibleFieldCount; } }
}
```
Source: https://stackoverflow.com/a/39798961/90287

Otherwise I don't know if a pull request with just a modified `GetBoolean` method will get accepted.

Thank you.

**Comment by moozzyk** [comment]
I might be wrong but I think the generic reader wouldn't work. There is no source reader for `CachingReader` - the data is read from an array that contains cached values from the original RecordSet. Even if it was possible, plumbing the generic reader and all the code bloat required to build it is not justified if it can be implemented with just 3 simple lines of code. It would be just unneeded complexity. 

Feel free to send a PR with the easy change. Please avoid double casting. I think this could look like this:

```C#
var value = GetValue(ordinal);
if (value is bool boolValue)
{
    return boolValue;
}
return (long)value != 0;
```

**Comment by moozzyk** [comment]
Thanks for the fix!
